version: "2.1"
services:
  mysqldb:
    image: mysql:8.0.17
    networks:
      - hotel-manager-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hotelmanager
    ports:
      - 3309:3309
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 60s
      timeout: 2s
      retries: 5
  hotel-manager:
    image: hotel-manager
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - hotel-manager-mysql
    depends_on:
      mysqldb:
        condition: service_healthy 
networks:
  hotel-manager-mysql: 